services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_ROOT_PASSWORD: tome
      POSTGRES_DATABASE: tome
      POSTGRES_USER: tome
      POSTGRES_PASSWORD: tome
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "5432:5432"

volumes: 
  db-data:
